### ISSUE TITLE
error ./node_modules/ts-logger-node/dist/index.mjs:2:0 Module not found: Can't resolve 'fs'

### ISSUE THREAD

**Issue by lritter79** [TylerSwindell/TSLogger#3]
<img width="1048" alt="Screen Shot 2023-07-29 at 12 21 55 AM" src="https://github.com/TylerSwindell/TSLogger/assets/12736541/6ba6d175-2c92-4fae-81e5-7e461911344c">
I got this error in a next.js project

**Comment by TylerSwindell** [comment]
Are the components server-side or are they client-side? 
Client-side won't support 'fs' do to it being a node module requiring access to the file system, not a browser-native package. 

Edit:
I can probably create a client-side version method that relays the message to the Next server in order to utilize 'fs'.

Edit2:

I also found a SO issue about something similar that might work for now. This is something I can probably implement as an optional feature for Next projects.
https://stackoverflow.com/questions/64926174/module-not-found-cant-resolve-fs-in-next-js-application

**Comment by lritter79** [comment]
I had the logger error in a file that solely contained functions and api calls, not any components. However, the functions were being called in a server component. The package worked as expected in my server components

**Comment by TylerSwindell** [comment]
So you only had an issue in a file that exported functions / API calls but not in actual server components? 
I'm just trying to grasp exactly where the problems are experienced and where there are no issues.
I'll try and recreate the issue and see what I can do!

**Comment by lritter79** [comment]
I was trying to call the logger in this file: https://github.com/lritter79/deck-builder-app/blob/main/src/app/functions/cardFunctions.ts

I’m using a function from this file in this server component: https://github.com/lritter79/deck-builder-app/blob/main/src/app/components/deck/deckComponent.tsx

**Comment by TylerSwindell** [comment]
After forking the repo I removed all instances of the ts-logger-node package and received the following build errors:
<img width="1270" alt="Screen Shot 2023-07-30 at 12 48 06 AM" src="https://github.com/TylerSwindell/TSLogger/assets/72827766/5332c852-8aa0-41cc-926e-b31e4daf47a2">


When I add the following options to your `next.config.js` I resolve the 'fs' errors.

`const nextConfig = {
  webpack5: true,
  webpack: (config) => {
    config.resolve.fallback = { fs: false };

    return config;
  },
}`

**Comment by TylerSwindell** [comment]
After forking the repo I added `ts-logger-node` to the files you specified and received the same errors you mentinoed.

I then removed all instances of the `ts-logger-node` package and received the following build errors:
<img width="1270" alt="Screen Shot 2023-07-30 at 12 48 06 AM" src="https://github.com/TylerSwindell/TSLogger/assets/72827766/5332c852-8aa0-41cc-926e-b31e4daf47a2">


When I add the following options to your `next.config.js` I resolve the `fs` errors but still receive the same errors as above.

```
const nextConfig = {
  webpack5: true,
  webpack: (config) => {
    config.resolve.fallback = { fs: false };

    return config;
  }
}
```

**Comment by TylerSwindell** [comment]
Adding this info to the docs for now, will try and add a Next option to the install.
